// <auto-generated />
using System;
using FinalLabSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalLabSystem.Migrations
{
    [DbContext(typeof(FinalLabDbContext))]
    [Migration("20260701010000_AddReportLayoutColumns")]
    partial class AddReportLayoutColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This Designer file is a minimal stub.
            // The full model snapshot is maintained in FinalLabDbContextModelSnapshot.cs.
            // Run 'dotnet ef migrations add' to regenerate the complete Designer file if needed.

#pragma warning restore 612, 618
        }
    }
}
